### ISSUE TITLE
ng-compile error

### ISSUE THREAD

**Issue by MurhafSousli** [tinesoft/generator-ngx-library#115]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### OS and Version?
 Windows 10

### Generator Version
4.4.0

### Tools Version

yo 2.0.0
node 8.4.0 
npm 5.3.0

### Targeted Angular version
4.x.x

### The log given by the failure.

![image](https://user-images.githubusercontent.com/8130692/32146598-bfe74046-bcea-11e7-8341-ab26d195752a.png)

Hi @tinesoft, I generated a new project after I updated to 4.4.0, it seems to be a problem with directories path

In **ng-compile**r task is accessing the files with wrong path
` Cannot find module '.componentsgallery-bulletsgallery-bullets.component'.`
instead of `components/gallery-bullets/gallery-bullets.component`

**Comment by MurhafSousli** [comment]
@tinesoft it was fixed after I cleared `node_modules` and npm install again
